# Generated by Django 5.2.8 on 2025-11-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('life', '일상'), ('hobby', '취미'), ('want', '버킷리스트')], default='life', max_length=20),
        ),
    ]
