# Generated by Django 5.2.8 on 2025-11-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('travel', '여행'), ('beauty', '뷰티')], default='free', max_length=20, verbose_name='카테고리'),
        ),
    ]
